UmbracoBuild/Cedar.Web/Controllers/NavigationSurfaceController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;
using Cedar.Web.Infrastructure.Data.Models.Folder;
using Cedar.Web.Infrastructure.Data.Models.Supplemental;
using Cedar.Web.Infrastructure.Data.ViewModels;
using Cedar.Web.Infrastructure.Extensions;
using umbraco.cms.presentation.Trees;
using Umbraco.Core.Models;
using Umbraco.Web;
using Umbraco.Web.Models;
using Cedar.UmbracoExtensions.Extensions;
using Cedar.Web.Infrastructure.Helpers;
using Umbraco.Web.Mvc;

namespace Cedar.Web.Controllers
{
    public class NavigationSurfaceController : SurfaceController
    {
        public ActionResult Header()
        {
            var header = NodeHelper.GetHeaderNavigation().As<Header>();
            var headerVm = header.Map();

            var currentSite = NodeHelper.GetCurrentSite();
            headerVm.SiteTitle = currentSite["Title"].ToString();

            var sites = NodeHelper.GetSites();
            headerVm.Sites = new List<SiteContainer>();            
            foreach (var site in sites)
            {
                var homepage = site.Children().First(x => x.DocumentTypeAlias.Equals("HomePage"));
                var domains = umbraco.library.GetCurrentDomains(homepage.Id);
                foreach (var domain in domains)
                {
                    var language = string.Empty;
                    if (domains.Count() > 1)
                    {
                        var cultureInfo = new CultureInfo(domain.DomainEntity.LanguageIsoCode);
                        var nativeName = cultureInfo.NativeName;
                        if (nativeName.Contains('('))
                        {
                            nativeName = nativeName.Remove(nativeName.IndexOf('(')).Trim();
                        }
                        language = string.Format(" ({0})", nativeName);
                    }

                    headerVm.Sites.Add(new SiteContainer
                    {
                        Title = site["Title"] + language,
                        Url = "//" + domain.Name
                    });
                }
            }

            var socialLinks = NodeHelper.GetSocialElements().Children();
            headerVm.SocialLinks = new List<ExternalLink>();
            foreach (var item in socialLinks)
            {
                headerVm.SocialLinks.Add(new ExternalLink
                {
                    Name = item.Name,
                    Class = item["Class"].ToString(),
                    Url = item["LinkUrl"].ToString()
                });
            }
            headerVm.LocalizedHomeUrl = NodeHelper.LogoLocalizedUrl(CurrentPage);
            return PartialView("~/Views/Partials/_Header.cshtml", headerVm);
        }

        public ActionResult Footer()
        {
            var footer = NodeHelper.GetFooterNavigation().As<Footer>();
            var footerVm = footer.Map();

            var socialLinks = NodeHelper.GetSocialElements().Children();
            footerVm.SocialLinks = new List<ExternalLink>();
            foreach (var item in socialLinks)
            {
                footerVm.SocialLinks.Add(new ExternalLink
                {
                    Name = item.Name,
                    Class = item["Class"].ToString(),
                    Url = item["LinkUrl"].ToString()
                });
            }

            return PartialView("~/Views/Partials/_Footer.cshtml", footerVm);
        }
    }
}

UmbracoBuild/Cedar.Web/Views/Shared/_Layout.cshtml
@using Cedar.UmbracoExtensions.Extensions
@inherits Umbraco.Web.Mvc.UmbracoViewPage<Cedar.Web.Infrastructure.Data.Models.BaseModel>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
    <meta name="description" content="@Model.MetaDescription">
    <title>@Model.MetaTitle | Cedar | Smart Content Marketing</title>
    
    @RenderSection("AdditionalMeta", required: false)
    
    <meta property="og:url" content="@Model.MetaUrl" />
    <meta property="og:type" content="@ViewBag.Type" />
    <meta property="og:title" content="@Model.MetaTitle" />
    <meta property="og:description" content="@Model.MetaDescription" />
    <meta property="og:image" content="@Model.MetaImage" />

    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="@Html.Raw("@cedarcontent")">
    <meta name="twitter:creator" content="@Html.Raw("@cedarcontent")">
    <meta name="twitter:title" content="@Model.MetaTitle">
    <meta name="twitter:description" content="@Model.MetaDescription">
    <meta name="twitter:image" content="@Model.MetaImage">

    <meta name="theme-color" content="#df1e54">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <link rel="icon" sizes="192x192" href="/images/icon-logo.png">
    <link rel="apple-touch-icon" href="/images/icon-logo.png">
    <meta name="apple-mobile-web-app-title" content="Cedar">

    <link rel="shortcut icon" href="/images/favicon.ico" type="image/x-icon">
    <link rel="preload" href="@Url.GetUrl("/styles/style.min.css")" as="style">
    <style>@RenderSection("PriorityStyles", required: true)</style>
    <noscript data-css-path="@Url.GetUrl("/styles/style.min.css")">
        <link rel="stylesheet" href="@Url.GetUrl("/styles/style.min.css")">
    </noscript>

    <script>
		(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		})(window,document,'script','@Url.GetAnalyticsUrl("/scripts/analytics.js")','ga');

        ga('create', 'UA-12426975-1', 'auto');
		ga('send', 'pageview');
	</script>
    <meta name="google-site-verification" content="7CSdQflQs2BewUer7k-TaltF8sWFPx2jMvX9RH6b818" />
</head>
<body class="@Model.BodyClass">
    <div class="page-wrapper oflow-hidden">
        @Html.Action("Header", "NavigationSurface")
        <div class="nav-offset"> 
            @RenderBody()
        </div>
        @Html.Action("Footer", "NavigationSurface")
    </div>
    
    @if (Model.FooterIncludes.ContainsKey("React"))
    {
        <script src="@Url.GetUrl("/scripts/react-lib/react-with-addons.min.js")"></script>
        <script src="@Url.GetUrl("/scripts/react-lib/react-dom.min.js")"></script>
    }
    @if (Model.FooterIncludes.ContainsKey("Slick"))
    {
        <script src="@Url.GetUrl("/scripts/react-lib/react-slick.min.js")"></script>
    }

    @if (Model.FooterIncludes.ContainsKey("Maps"))
    {
        <script src="//maps.googleapis.com/maps/api/js?key=AIzaSyD1McX_HRYIXkCKc9enLajQNf8fWh52UHs"></script>
    }
    @if (Model.FooterIncludes.ContainsKey("TwitterIntents"))
    {
        <script src="//platform.twitter.com/widgets.js" async></script>
    }
    <script src="@Url.GetUrl("/scripts/script.min.js")" async></script>
</body>
</html>