UmbracoBuild/Cedar.Web/Controllers/FormSurfaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Cedar.Web.Infrastructure.Data.ViewModels;
using Umbraco.Core.Services;
using umbraco.NodeFactory;
using Umbraco.Web;
using Umbraco.Web.Mvc;

namespace Cedar.Web.Controllers
{
    public class FormSurfaceController : SurfaceController
    {
        [HttpPost]
        public JsonResult Contact(CtaMessageUsVm message)
        {
            const int formId = 1401;

            if (ModelState.IsValid)
            {
                try
                {
                    var referrer = HttpContext.Request.UrlReferrer != null ? HttpContext.Request.UrlReferrer.ToString() : string.Empty;

                    var contentService = Services.ContentService;
                    var content = contentService.CreateContent(DateTime.Today.ToString("yy/MM/dd"), formId, "ContactFormSubmission");
                    content.SetValue("name", message.Name);
                    content.SetValue("jobTitle", message.JobTitle);
                    content.SetValue("email", message.Email);
                    content.SetValue("message", message.Message);
                    content.SetValue("urlReferrer", referrer);
                    contentService.Save(content);

                    var helper = new UmbracoHelper(UmbracoContext.Current);
                    var formFolder = helper.TypedContent(formId);
                    var sendEmailsFrom = formFolder.GetPropertyValue<string>("emailFrom");
                    var sendEmailsTo = formFolder.GetPropertyValue<string>("emailTo");

                    var body = String.Format("<p>New contact form submission</p><p>Name: {0}<br />Job Title: {1}<br />Email: {2}<br />Message: {3}<br />Url: {4}</p>", 
                        message.Name, 
                        message.JobTitle, 
                        message.Email,
                        message.Message.Replace("\n", "<br />"),
                        referrer);
                    var subject = "Cedar Contact Form - Message Sent " + DateTime.Today.ToString("yy/MM/dd");

                    umbraco.library.SendMail(sendEmailsFrom, sendEmailsTo, subject, body, true);

                    return Json(new { Result = true });
                }
                catch (Exception ex)
                {
                    // send a different message for an exception?
                }
            }
            return Json(new { Result = false });
        }
    }
}

UmbracoBuild/Cedar.Web/Views/Partials/Shared/Banner.cshtml
@model Cedar.Web.Infrastructure.Data.ViewModels.BannerVm

@if (!Object.ReferenceEquals(Model.Image, Umbraco.Core.Dynamics.DynamicNull.Null))
{
    <div class="img-container oflow-hidden desktop">
        @{ 
            String backgroundPosition = (Model.BackgroundPosition == null) ? "top center" : Model.BackgroundPosition;
        }
        <div style="background-image:url(@Model.Image); background-position:@backgroundPosition">
            <div class="ratio"></div>
        </div>
    </div>
    <div class="img-container mobile">
        <div style="background-image:url(@Model.MobileImage)" class="ratio"></div>
    </div>
}
@if (!string.IsNullOrEmpty(Model.Title))
{
    <div class="tab posrel box-size">
        <div class="container max1000 no-side-pad cms">
            @if (!Object.ReferenceEquals(Model.Logo, Umbraco.Core.Dynamics.DynamicNull.Null))
            {
                <div class="logo-wrapper display-table marginbot1 width-100">
                    <div class="display-tcell valign-mid">
                        <img class="logo" src="@Model.Logo.Url" alt="@Model.Logo.Name">
                    </div>
                </div>
            }
            <h1>@Model.Title</h1>
            @if (!string.IsNullOrEmpty(Model.SubTitle))
            {
                <p class="subhead text-center primary-font">@Model.SubTitle</p>
            }
        </div>
    </div>
}

@if (!string.IsNullOrEmpty(Model.IntroText))
{
    <div class="container max1000">
        @Html.Raw(Model.IntroText)
    </div>
}

UmbracoBuild/Cedar.Web/Views/Partials/Shared/BannerWithLogo.cshtml
@model Cedar.Web.Infrastructure.Data.ViewModels.BannerWithLogoVm

@if (!string.IsNullOrEmpty(Model.Image))
{
    <div class="img-container oflow-hidden desktop">
        <div style="background-image:url(@Model.Image.Url)" class="bg-img-top ratio"></div>
    </div>
}
@if (!string.IsNullOrEmpty(Model.MobileImage))
{
    <div class="img-container mobile">
        <div style="background-image:url(@Model.MobileImage.Url)" class="ratio"></div>
    </div>
}
@if (!string.IsNullOrEmpty(Model.Title))
{
    <div class="tab posrel box-size">
        <div class="container max1000 no-side-pad">
            @if (!string.IsNullOrEmpty(Model.Logo))
            {
                <div class="logo-wrapper display-table marginbot1 width-100">
                    <div class="display-tcell valign-mid">
                        <img class="logo" src="@Model.Logo.Url" alt="@Model.Logo.Name">
                    </div>
                </div>
            }
            <h1>@Model.Title</h1>
            @if (!string.IsNullOrEmpty(Model.SubTitle))
            {
                <p class="subhead text-center colour-g">@Model.SubTitle</p>
            }
        </div>
    </div>
}

UmbracoBuild/Cedar.Web/Views/Partials/Shared/CTAFollow.cshtml
@model Cedar.Web.Infrastructure.Data.ViewModels.CtaFollowVm

<section class="container text-center bg-grey footer-cta cta-social">
    <h2 class="colour-b">@library.GetDictionaryItem("More from Cedar")</h2>
    <ul class="social no-pad no-mar flex fjustcntr padtop05">
        @foreach (var link in Model.SocialLinks)
        {
            <li><a href="@link.Url" data-event-category="Social follow" data-event-action="@link.Name" data-event-label="CTA" target="_blank" class="@link.Class text-indent block circle">@link.Name</a></li>
        }
    </ul>
</section>

UmbracoBuild/Cedar.Web/Views/Partials/Shared/CTAMessageUs.cshtml
@model Cedar.Web.Infrastructure.Data.ViewModels.CtaMessageUsVm

<section class="container text-center bg-grey footer-cta posrel">
    <div class="extra-pad">
        <h2 class="colour-b">@library.GetDictionaryItem("CtaMessageUsTitle")</h2>
        <p>@Html.Raw(library.GetDictionaryItem("CtaMessageUsSummary"))</p>
        <button class="button-reset btn btn-primary panel1 margintop2" id="message-btn">@library.GetDictionaryItem("CtaMessageUsMessageButton")</button>

        <div id="contact-wrapper" class="accordion panel2 padright2 padleft2 box-size height-100 flex fcol fjustcntr">
            <form action="@Url.Action("Contact", "FormSurface")" id="contact-form" class="contact-form flex frow fwrap">
                <label class="box-size">
                    @Html.TextBoxFor(x => x.Name, new { @class = "box-size", @placeholder = library.GetDictionaryItem("CtaMessageUsNameLabel"), @required = "" })
                </label>
                <label class="box-size">
                    @Html.TextBoxFor(x => x.JobTitle, new { @class = "box-size", @placeholder = library.GetDictionaryItem("CtaMessageUsJobTitleLabel"), @required = "" })
                </label>
                <label>
                    @Html.TextBoxFor(x => x.Email, new { @class = "box-size", @placeholder = library.GetDictionaryItem("CtaMessageUsJobEmailLabel"), @required = "" })
                </label>
                <label>
                    @Html.TextAreaFor(x => x.Message, new { @class = "box-size", @placeholder = library.GetDictionaryItem("CtaMessageUsJobMessageLabel"), @required = "" })
                </label>
                <input id="message-submit" type="submit" value="@library.GetDictionaryItem("CtaMessageUsSendButton")" class="button-reset btn btn-primary">
                <span id="contact-form-error" class="hide">@library.GetDictionaryItem("CtaMessageUsError")</span>
            </form>
        </div>
    </div>
    <div class="panel3 opacity0 posabsolute padright2 padleft2 box-size height-100 flex fcol fjustcntr">
        <h2 class="colour-b">@library.GetDictionaryItem("CtaMessageUsSuccessTitle")</h2>
        <p class="font180">@Html.Raw(library.GetDictionaryItem("CtaMessageUsSuccessSummary"))</p>
    </div>
</section>

UmbracoBuild/Cedar.Web/Views/Partials/Shared/CTANewsletter.cshtml
<section id="footer-newsletter" class="container text-center bg-grey footer-cta posrel">
    <div id="footer-newsletter-form" class="panel1">
        <h2 class="colour-b">@library.GetDictionaryItem("CtaNewsletterTitle")</h2>
        <p class="font110 marginbot2">@Html.Raw(library.GetDictionaryItem("CtaNewsletterSummary"))</p>
        <form action="//cedarcommunicationsltd.createsend.com/t/j/s/tjhukk/" class="inline-form shadow" id="newsletter-signup">
            <label class="flex fgrow1"><input id="fieldEmail" type="email" placeholder="@library.GetDictionaryItem("CtaNewsletterEmailPlaceholder")" required></label>
            <input type="submit" value="@library.GetDictionaryItem("CtaNewsletterSignUpButton")" class="button-reset btn btn-primary" id="footer-newsletter-submit">
        </form>
    </div>
    <div id="footer-newsletter-fb" class="panel2 opacity0 posabsolute padright2 padleft2 box-size height-100 flex fcol fjustcntr">
        <h2 class="colour-b">@library.GetDictionaryItem("CtaNewsletterSuccessTitle")</h2>
        <p class="font180 no-mar">@Html.Raw(library.GetDictionaryItem("CtaNewsletterSuccessSummary"))</p>
    </div>
</section>

UmbracoBuild/Cedar.Web/Views/Partials/Shared/CaseStudiesList.cshtml
@model Cedar.Web.Infrastructure.Data.ViewModels.CaseStudiesListVm

<!-- Promo List -->
<section class="container col2 no-side-pad">
    <h2>@Model.Title</h2>
    <ul class="promo-list no-pad flex frow fwrap">
        @foreach (var caseStudy in Model.CaseStudies)
        {
            var img = UmbracoContext.Current.MediaCache.GetById(caseStudy.Image);

            <li class="text-center col box-size flex">
                <a href="@caseStudy.Url" class="fgrow1 flex fcol width-100">
                    <div class="img-wrapper-16-9 oflow-hidden">
                        <div class="img-zoom" style="background-image:url('@img.GetPropertyValue("UmbracoFile")?width=684&amp;height=385')"></div>
                    </div>
                    <div class="content box-size flex fcol fgrow1">
                        <span class="colour-d text-upper primary-font">@caseStudy.PrimarySite.Title</span>
                        <h3>@caseStudy.NavigationTitle</h3>
                        <p class="width-100 fgrow1">@caseStudy.Description</p>
                        <div class="btn btn-primary-on-hover">@library.GetDictionaryItem("Read More")</div>
                    </div>
                </a>
            </li>
        }
    </ul>
    @if (!Object.ReferenceEquals(Model.Link, Umbraco.Core.Dynamics.DynamicNull.Null))
    {
        <a href="@Model.Link.Url" class="btn btn-primary margintop2 marginbot1">@Model.LinkTitle</a>
    }
</section>

UmbracoBuild/Cedar.Web/Views/Partials/Shared/GridContent.cshtml
@using Cedar.UmbracoExtensions.Extensions
@model Cedar.Web.Infrastructure.Data.ViewModels.GridContentVm

@Html.GetVortoGridHtml(Model.Content, "Content", Model.Framework)

UmbracoBuild/Cedar.Web/Views/Partials/Shared/JobsList.cshtml
@model Cedar.Web.Infrastructure.Data.ViewModels.JobsListVm

<section class="no-top-pad no-pad">
    <div class="container max1000">
        <ul class="join">
            @foreach (var job in Model.Jobs)
            {
                <li>
                    <h2 class="accordion text-left no-mar">@job.JobTitle <span class="black">@job.Location</span></h2>
                    <div>@Html.Raw(job.Description)</div>
                </li>
            }
        </ul>
    </div>
</section>

UmbracoBuild/Cedar.Web/Views/Partials/Shared/MediaList.cshtml
@model Cedar.Web.Infrastructure.Data.ViewModels.MediaListVm

<section class="bg-grey no-mar">
    <div class="container">
        <h2>@Model.Title</h2>
        <ul class="col4-one-row no-pad flex media-list articles-list frow fwrap fjustcntr margintop1-5 margin-auto">
            @foreach (var mediaItem in Model.MediaItems)
            {
                var img = UmbracoContext.Current.MediaCache.GetById(mediaItem.Image);
                
                <li class="col flex box-size padleft05 padright05 marginbot1">
                    <a href="@mediaItem.Link" class="flex fcol" target="_blank">
                        <div class="img-wrapper-62-25 oflow-hidden">
                            <img src="@img.GetPropertyValue("UmbracoFile")?width=620&amp;height=250" />
                        </div>
                        <div class="padleft1 padright1 padbot1 flex fgrow1 fcol">
                            <span class="colour-d text-upper primary-font text-center font80 letter-spacing block padbot05">@mediaItem.Title</span>
                            <p class="fgrow1">@mediaItem.Summary</p>
                            <div class="btn-more text-center">
                                <div class="text-upper btn-primary-on-hover primary-font">@library.GetDictionaryItem("Read more")</div>
                            </div>
                        </div>
                    </a>
                </li>
            }
        </ul>
    </div>
</section>

UmbracoBuild/Cedar.Web/Views/Partials/Shared/RichTextContent.cshtml
@model Cedar.Web.Infrastructure.Data.ViewModels.RichTextContentVm

<section class="no-top-pad no-pad">
    <div class="container max1000">
        @Html.Raw(Model.Content)
    </div>
</section>

UmbracoBuild/Cedar.Web/Views/Partials/Shared/ServicesList.cshtml
@model Cedar.Web.Infrastructure.Data.ViewModels.ServicesListVm

<!-- Grid with inlined details panel (4 column grid) -->
<div id="details-grid" data-primarystyles="details-grid col4 no-pad no-mar" data-secondarystyles="img-wrapper-16-9" data-feed="/umbraco/surface/ComponentsSurface/JsonServicesList/@Model.DataSourceId">
    <!-- Add any React generated classes here so that PurifyCSS doesn't remove them -->
    <span class="react-anim-accordion-enter react-anim-accordion-enter-active react-anim-accordion-leave react-anim-accordion-leave-active"></span>
</div>

@{ ViewBag.React = "true"; }

UmbracoBuild/Cedar.Web/Views/Partials/Shared/TechnologiesList.cshtml
@model Cedar.Web.Infrastructure.Data.ViewModels.TechnologiesListVm

<section class="no-pad no-mar">
    <div class="container max1000 box-size padleft1 padright1">
        <h2>@Model.Title</h2>
        <div class="col3 flex fwrap fjustcntr frow headings-small padbot0 sidemargin-neg1 no-bullets text-center partners">
            @foreach (var tech in Model.Technologies)
            {
                var img = UmbracoContext.Current.MediaCache.GetById(tech.Logo);
                
                <div class="col padleft1 padright1 marginbot1 box-size">
                    <img src="@img.GetPropertyValue("UmbracoFile")?height=180" alt="">
                    @Html.Raw(tech.Content)
                </div>
            }
        </div>

    </div>
</section>

UmbracoBuild/Cedar.Web/Views/Partials/Shared/TweetsList.cshtml
@using Our.Umbraco.uTwit
@model Cedar.Web.Infrastructure.Data.ViewModels.TweetsListVm

<section class="container">
    <h2>@Model.Title</h2>
    <ul class="flex tweets margin-auto col3sm">
        @foreach (var tweet in Model.Tweets)
        {
            <li class="flex col fcol box-size">
                <div class="colour-d text-center marginbot0-5 primary-font">@uTwit.FormatDate(tweet.CreatedAt)</div>
                <p class="fgrow1" data-tweet="text">@tweet.LinkifiedText</p>
                <ul class="flex frow width-100">
                    <li>
                        <a href="https://twitter.com/intent/tweet?in_reply_to=@tweet.Id" class="text-indent block margin-auto" target="_blank" data-event-category="Tweet" data-event-action="Reply">Reply</a>
                    </li>
                    <li>
                        <a href="https://twitter.com/intent/retweet?tweet_id=@tweet.Id" class="text-indent block margin-auto" target="_blank" data-event-category="Tweet" data-event-action="Retweet">Re-Tweet</a>
                    </li>
                    <li>
                        <a href="https://twitter.com/intent/like?tweet_id=@tweet.Id" class="text-indent block margin-auto" target="_blank" data-event-category="Tweet" data-event-action="Like">Like</a>
                    </li>
                </ul>
            </li>
        }
    </ul>
</section>

UmbracoBuild/Cedar.Web/Views/Partials/Shared/WhitePapersList.cshtml
@model Cedar.Web.Infrastructure.Data.ViewModels.WhitePapersListVm

<section class="whitepaper container max1000 box-size">
    <h2>@Model.Title</h2>
    @foreach (var whitePaper in Model.WhitePapers)
    {
        var img = UmbracoContext.Current.MediaCache.GetById(whitePaper.Thumb);
        var download = UmbracoContext.Current.MediaCache.GetById(whitePaper.Download);
        var article = UmbracoContext.Current.ContentCache.GetById(whitePaper.RelatedArticle);
        
        <div class="flex">
            <div class="img-wrap padright1">
                <img src="@img.GetPropertyValue("UmbracoFile")?width=500&amp;height=500" alt="">
            </div>
            <div>
                <h3 class="text-left font140">@whitePaper.Title</h3>
                <p>@whitePaper.Summary</p>
                @if (download != null)
                {
                    <a href="@download.GetPropertyValue("UmbracoFile")" target="_blank" class="btn btn-primary inline-block">@library.GetDictionaryItem("Download")</a>
                }
                @if (article != null)
                {
                    <a href="@article.Url" class="text-upper inline-block primary-font">More about this whitepaper</a> @* TO DO *@
                }
            </div>
        </div>
    }
</section>